// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgrKjmymDGX88gGyuPJ2CCj18fLxUFZrw',
    appId: '1:458682327472:web:6e45e4fa0ba8c31dbcf675',
    messagingSenderId: '458682327472',
    projectId: 'wisata-indonesia-130a0',
    authDomain: 'wisata-indonesia-130a0.firebaseapp.com',
    databaseURL: 'https://wisata-indonesia-130a0-default-rtdb.firebaseio.com',
    storageBucket: 'wisata-indonesia-130a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBOeHjVWsrCSB5gtYc4xnj5Y8JVvXDDZo',
    appId: '1:458682327472:android:dfb7719668e144d0bcf675',
    messagingSenderId: '458682327472',
    projectId: 'wisata-indonesia-130a0',
    databaseURL: 'https://wisata-indonesia-130a0-default-rtdb.firebaseio.com',
    storageBucket: 'wisata-indonesia-130a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJOJr0adzlHefujOLrd5DfQNnYWjVgRwE',
    appId: '1:458682327472:ios:59c7255e2d65fde2bcf675',
    messagingSenderId: '458682327472',
    projectId: 'wisata-indonesia-130a0',
    databaseURL: 'https://wisata-indonesia-130a0-default-rtdb.firebaseio.com',
    storageBucket: 'wisata-indonesia-130a0.appspot.com',
    iosClientId: '458682327472-30049aj0tmoocsvd91vva0b6jd20vhh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.wni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJOJr0adzlHefujOLrd5DfQNnYWjVgRwE',
    appId: '1:458682327472:ios:59c7255e2d65fde2bcf675',
    messagingSenderId: '458682327472',
    projectId: 'wisata-indonesia-130a0',
    databaseURL: 'https://wisata-indonesia-130a0-default-rtdb.firebaseio.com',
    storageBucket: 'wisata-indonesia-130a0.appspot.com',
    iosClientId: '458682327472-30049aj0tmoocsvd91vva0b6jd20vhh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.wni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgrKjmymDGX88gGyuPJ2CCj18fLxUFZrw',
    appId: '1:458682327472:web:eaab63b8f0aec1b4bcf675',
    messagingSenderId: '458682327472',
    projectId: 'wisata-indonesia-130a0',
    authDomain: 'wisata-indonesia-130a0.firebaseapp.com',
    databaseURL: 'https://wisata-indonesia-130a0-default-rtdb.firebaseio.com',
    storageBucket: 'wisata-indonesia-130a0.appspot.com',
  );
}
